### ISSUE TITLE
image

### ISSUE THREAD

**Issue by kento980037** [fujino-and-fujino/cowork-video-room#8]
<img width="875" alt="github_image1" src="https://user-images.githubusercontent.com/82075582/138822254-6e9df46a-e152-4970-bf1d-17283be056ff.png">

![github_image2](https://user-images.githubusercontent.com/82075582/138822279-990085d0-7d3e-43aa-9d23-11b827c667cf.gif)

![github_image3](https://user-images.githubusercontent.com/82075582/138823944-b279c01b-d428-4d2b-a0ca-07c37c417a56.gif)

**Comment by Yutarotaro** [comment]
追加した
